### ISSUE TITLE
How to use R model?

### ISSUE THREAD

**Issue by yo-ii** [yoshida-lab/XenonPy#138]
In the last part of XenonPy/samples/mdl.ipynb, it is announced the R tutorials will be released.
I want to use the R model, since the python model is available only for inorganic crystals.
Please disclose how to calculated the fingerprint value input to the R model. 
If there is some reference code, it is ok.

**Comment by TsumiNa** [comment]
Hi, @yo-ii. All R models are maintained by other guys, so we need more time to wait for his docs, please be patient. Also, we are planning to retrain all R models in python to improve the consistency of our interface.

**Comment by yo-ii** [comment]
Is it now available to use R models or retrained models for python?

**Comment by TsumiNa** [comment]
@yo-ii We are training organic models in Python. These will include data from `QM9`, `Polymer Genome`, and so on. These tasks still need more time, but when it finished you will never need to run codes in R.

**Comment by TsumiNa** [comment]
@yo-ii Also, see [this tutorial](https://xenonpy.readthedocs.io/en/latest/tutorials/5-pre-trained_model_library.html) to learn how to use new APIs.
