### ISSUE TITLE
BaseDescriptor does not have feature_labels

### ISSUE THREAD

**Issue by stewu5** [yoshida-lab/XenonPy#211]
BaseDescriptor and BaseFeaturizer are not completely compatible to each other, 
as BaseDescriptor does not have feature_labels to be called.
Instead, it relies on simply concatenating the results of BaseFeaturizers,
i.e., pre-extraction of the column names are not possible.

**Comment by TsumiNa** [comment]
Hi @stewu5! I think adding this feature to BaseDescriptor is simple work, but do you really need this feature? Could you give me a scene you have to use this feature?

**Comment by stewu5** [comment]
This is a consistent issue, I think. There are times that we need to extract the column names of the output dataframe after transformation using BaseFeaturizer, which means that would be the same scenario for BaseDescriptor. As an example, we want to write a new BaseFeaturizer, such as the dataframe wrapper or the frozenfeaturizer wrapper, we now need to save the output in order to get the feature column names because direct extraction of the names is only possible for BaseFeaturizer but not the BaseDescriptor, while our input for those wrapper can accept both.

**Comment by TsumiNa** [comment]
@stewu5 Yes, the consistent. Let's add this feature.
