### ISSUE TITLE
how to train the pre-trained model in XenonPy.MDL

### ISSUE THREAD

**Issue by yyamaguchi** [yoshida-lab/XenonPy#234]
I read your paper (https://pubs.acs.org/doi/10.1021/acscentsci.9b00804), but I couldn't understand much of the details because I am not familiar with this field, so please tell me how to train the learned model in XenonPy.MDL.

First of all, are you doing early stopping during this training process?
Also, are you training using all the data instead of splitting it into training and test data? If so, do you mean that the MAE and MSE that are calculated are not the values when cross-validated?

**Comment by TsumiNa** [comment]
@yyamaguchi We are so glad that you are interested in our paper and also I would like to explain to you the details of our model training. Please understand that the issues on Github focus on the XenonPy package, so could you leave me your working email if possible? Then, I will contact you ASAP.

It's also possible to contact me via this address liu.chang@ism.ac.jp directly.

**Comment by yyamaguchi** [comment]
@TsumiNa 
Thank you for your reply.
I understand the contents of your reply.I will contact you directly on your email.

**Comment by TsumiNa** [comment]
@yyamaguchi Thank you for contacting me. I will reply to you ASAP.
