### ISSUE TITLE
Is there any documentation for units?

### ISSUE THREAD

**Issue by AcylSilane** [yoshida-lab/XenonPy#245]
Thanks for this awesome package - it's incredibly useful! Is there any documentation on the units for the various features listed on https://xenonpy.readthedocs.io/en/latest/features.html ?

**Comment by stewu5** [comment]
@AcylSilane Sorry for the delayed reply. 
For rdkit descriptors, we simply provide a wrapper for it, so we recommend looking up at the rdkit page.
For our own descriptors, @TsumiNa Can you provide the information for the composition descriptors?

**Comment by AcylSilane** [comment]
Hi @stewu5, no worries. Thanks for getting back to me! The RDKit documentation was informative for that set of features; looking forward to learning more about the compositional descriptors as well.

**Comment by stewu5** [comment]
@AcylSilane here is the source for the units (attached PDF)
this information is supposed to be included and will be updated in this paper: https://onlinelibrary.wiley.com/doi/full/10.1002/adma.202102507

[element_features.pdf](https://github.com/yoshida-lab/XenonPy/files/7642440/element_features.pdf)

**Comment by AcylSilane** [comment]
@stewu5 Thank you! This is exactly what I was looking for.

**Comment by TsumiNa** [comment]
It seems no questions are here. Just close this issue 😄
